'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function read(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
function save(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch{toast('Storage is full. Please remove older entries.');return false}}
let profile=read('az-profile',{}),entries=read('az-journal',[]),messages=[],page='home',busy=false,generation=0;
const connected=false;
const rashis=['Not sure','Mesha · Aries','Vrishabha · Taurus','Mithuna · Gemini','Karka · Cancer','Simha · Leo','Kanya · Virgo','Tula · Libra','Vrischika · Scorpio','Dhanu · Sagittarius','Makara · Capricorn','Kumbha · Aquarius','Meena · Pisces'];
const lessons=[
 ['01','The birth chart','A map, a moment, a tradition','A Janma Kundli maps celestial positions for a birth time and location within a chosen astrological system. In Vedic practice, the sidereal zodiac is commonly used. Accurate chart work requires a reliable astronomical calculation engine, time-zone handling and a specified ayanamsha. Astro Zero does not calculate a Kundli in this preview.'],
 ['02','Rashi & Lagna','Two different perspectives','Rashi often refers to the sign occupied by the Moon in Vedic readings. Lagna is the rising sign at the eastern horizon for the place and moment of birth. They are not interchangeable, and your birth date alone is not enough to reliably determine them.'],
 ['03','The nine grahas','Symbols in Vedic astrology','The navagraha are Surya, Chandra, Mangala, Budha, Guru, Shukra, Shani, Rahu and Ketu. Rahu and Ketu are lunar nodes, not physical planets. Traditional interpretations associate these grahas with different themes of life. These associations are cultural beliefs, not scientifically established predictors.'],
 ['04','Nakshatras','The lunar mansions','A common Vedic system divides the zodiac into 27 nakshatras. Each spans 13 degrees and 20 minutes. The Moon’s precise position determines the birth nakshatra; a verified astronomical calculation is needed before giving a personal result.'],
 ['05','Dashas & timing','A traditional lens on cycles','Dasha systems describe symbolic periods associated with grahas. Vimshottari is one commonly used system. A personal sequence depends on the Moon’s birth position and other calculation choices. Treat interpretations as reflection rather than certainty about events.'],
 ['06','Mindful practice','Keep your agency','Use a reading as an invitation to reflect. Avoid fear-driven decisions, expensive remedies or guaranteed outcomes. You do not need to buy gemstones or rituals to use this app. For health, legal or financial decisions, seek qualified professional advice.']
];
const reflections=['Make room for one thoughtful pause before your next decision.','Notice what restores your energy, and give it a little more space.','Choose one small promise to yourself that you can keep today.','A clear conversation begins with patient listening.','Let curiosity lead before you reach for a conclusion.','Return to something simple: a walk, a breath, a page.','Progress can be quiet. Notice what is already growing.'];
const content=$('#content');
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').style.display='none',3500)}
function navigate(p){if(!['home','explore','chat','journal','profile','privacy'].includes(p))p='home';if(location.hash!=='#'+p)history.pushState(null,'','#'+p);page=p;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===p));render();window.scrollTo(0,0)}
window.goHome=()=>{if(page==='home')return true;navigate('home');return false};
function heading(k,t,d){return `<div class="eyebrow">${k}</div><h1>${t}</h1><p>${d}</p>`}
function render(){
 if(page==='home'){
 const d=new Date();content.innerHTML=heading(d.toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long'}),`A little cosmic<br>perspective${profile.name?', '+esc(profile.name):''}.`,'Ancient wisdom. A moment for yourself.')+`<section class="hero"><div class="row"><span class="badge">✦ VEDIC WISDOM</span><span class="tiny muted">ASTRO ZERO</span></div><div class="sky" aria-hidden="true"><span class="star s1">✦</span><div class="orbit"><span class="sun">☉</span></div><span class="star s2">✧</span><span class="star s3">✦</span></div><div class="eyebrow">A DAILY REFLECTION</div><h2>Your day begins<br>with intention.</h2><p>${reflections[d.getDay()]}</p><button class="button full" data-nav="journal">Set your intention <span aria-hidden="true">↗</span></button></section><div class="row section"><h2>Your personal space</h2><button class="textbutton" data-nav="profile">${profile.name?'Edit profile':'Get started'} ↗</button></div><div class="grid"><button class="card" data-nav="chat"><div class="symbol">✧</div><h3>Ask Astro Zero</h3><p>${connected?'Explore with your AI guide':'AI guide · setup pending'}</p></button><button class="card" data-nav="explore"><div class="symbol">☷</div><h3>Vedic essentials</h3><p>Small lessons. Deeper insight.</p></button></div><div class="card wide"><div class="eyebrow">YOUR MOON SIGN</div><h2 style="margin-top:8px">${esc(profile.rashi&&profile.rashi!=='Not sure'?profile.rashi:'A story to discover')}</h2><p>${profile.rashi&&profile.rashi!=='Not sure'?'Self-reported in your profile.':'Add your known Rashi in your profile. A calculated birth chart is not available yet.'}</p></div><p class="tiny muted">For reflection and entertainment. Daily reflections are editorial prompts, not planetary predictions.</p>`;
 }
 if(page==='explore')content.innerHTML=heading('THE VEDIC LIBRARY','A universe of<br>understanding.','Start with the foundations. Explore at your own pace.')+`<div class="notice">Educational content. These traditions are not scientifically validated methods of predicting events.</div>`+lessons.map((l,i)=>`<button class="card wide row" style="width:100%" data-lesson="${i}"><span class="number">${l[0]}</span><span style="flex:1"><h3>${l[1]}</h3><p>${l[2]}</p></span><span>↗</span></button>`).join('');
 if(page==='profile')content.innerHTML=heading('YOUR COSMIC PROFILE','Made personal.','Your details stay in this browser. No account needed.')+`<form id="profile-form"><label for="name">First name or nickname</label><input id="name" name="name" maxlength="35" autocomplete="given-name" value="${esc(profile.name)}"><label for="birth">Date of birth (optional)</label><input id="birth" name="birth" type="date" max="${new Date().toLocaleDateString('en-CA')}" value="${esc(profile.birth)}"><div class="fieldrow"><div><label for="time">Birth time (optional)</label><input id="time" name="time" type="time" value="${esc(profile.time)}"></div><div><label for="rashi">Known Moon sign</label><select id="rashi" name="rashi">${rashis.map(r=>`<option ${profile.rashi===r?'selected':''}>${r}</option>`).join('')}</select></div></div><label for="place">Birthplace (optional)</label><input id="place" name="place" maxlength="100" value="${esc(profile.place)}" placeholder="City, country"><p class="tiny muted" style="margin-top:12px">We do not infer your Rashi from your birthday. Birth details are stored for your reference; chart calculation is not included.</p><button class="button full">Save profile</button></form><div class="divider"></div><button class="textbutton" data-nav="privacy">Privacy & app information ↗</button><br><button class="textbutton danger" id="delete-all">Delete all data in this browser</button><p class="tiny muted">Web preview 1.0 · ${connected?'AI service configured':'AI service not connected'}</p>`;
 if(page==='journal')content.innerHTML=heading('YOUR REFLECTION JOURNAL','A moment,<br>just for you.','Collect intentions, small discoveries and fresh perspectives.')+`<form id="journal-form"><label for="intention">What would you like to make space for today?</label><textarea id="intention" maxlength="2000" required placeholder="Today, I want to…"></textarea><button class="button full">Save reflection</button></form><div class="row section"><h2>Your reflections</h2><span class="tiny muted">${entries.length} saved</span></div>`+(entries.length?entries.map(e=>`<article class="card wide"><div class="row"><span class="eyebrow">${esc(new Date(e.date).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'}))}</span><button class="textbutton danger" data-delete="${e.id}" aria-label="Delete reflection">Delete</button></div><p class="entry">${esc(e.text)}</p></article>`).join(''):`<div class="empty"><div class="symbol">▤</div><h2>Your story starts here.</h2><p class="tiny">Only you can see what you save in this browser.</p></div>`);
 if(page==='chat')content.innerHTML=heading('YOUR AI ASTROLOGY GUIDE','Let’s find<br>some perspective.','Ask about Vedic concepts or explore a question on your mind.')+`<div class="notice">${connected?'AI can make mistakes. No verified birth chart is available, so this guide cannot provide personal planetary placements or timing predictions.':'AI consultations are not connected in this preview. Explore the Vedic library and journal while the service is being prepared.'}</div><div class="chips">${['What is my Rashi?','Explain the nine grahas','How can I set an intention?'].map(x=>`<button class="chip" data-prompt="${esc(x)}">${x}</button>`).join('')}</div><div id="messages">${messages.map((m,i)=>`<article class="message ${m.role==='user'?'user':''}"><div class="role">${m.role==='user'?'YOU':'ASTRO ZERO · AI'}</div>${esc(m.content)}${m.role==='assistant'?`<div><button class="textbutton" data-report="${i}">Report response</button></div>`:''}</article>`).join('')}</div><form id="chat-form"><label for="question">Your question</label><textarea id="question" required maxlength="1500" placeholder="What would you like to explore?" ${!connected?'disabled':''}></textarea><label class="check"><input type="checkbox" id="consent" ${read('az-consent',false)?'checked':''} ${!connected?'disabled':''}><span>I agree to send my question and recent chat to the AI service (Cloudflare). My birth profile and journal are not sent. <button type="button" class="textbutton" data-nav="privacy">Privacy details</button></span></label><button class="button full" ${!connected||busy?'disabled':''}>${busy?'Thinking…':connected?'Send question ↗':'AI setup pending'}</button></form><p class="tiny muted" style="margin-top:16px">Chat is kept only for this session. Avoid sharing sensitive personal information.</p>`;
 if(page==='privacy')content.innerHTML=heading('PRIVACY & TRANSPARENCY','Your space.<br>Your choices.','Astro Zero · web preview 1.0')+`<div class="learn"><h2>Stored on your device</h2><p>Your optional birth profile, reflections and AI consent preference are stored in app storage. There are no ads, analytics, location requests or accounts. Clearing browser storage removes your saved data. The hosting service processes normal web requests; this app has no analytics trackers.</p><h2>AI consultations</h2><p>${connected?'The AI service is configured.':'The AI service is not connected in this preview.'} Once connected, sending a message requires your consent. Your question and up to six recent messages go to the developer’s Cloudflare service and Workers AI. Your profile and journal are not sent. The service processes the network IP address for rate limiting. Provider processing is subject to Cloudflare’s terms.</p><h2>Response reports</h2><p>Reporting sends the selected AI response and your chosen reason to the developer’s service for review. The supplied backend keeps reports for 30 days. A report is confirmed only when the server accepts it.</p><h2>Delete or withdraw</h2><p>Use “Delete all data” in your profile to remove local details, journal, chat and consent. This cannot delete reports already sent to the service. For privacy questions, contact Dipa Boruah Phukon at dipaboruahphukon59@gmail.com. A public privacy policy must be published before launch.</p><h2>Use with perspective</h2><p>Astrology is a cultural and spiritual tradition, not a scientifically established predictive method. Content is for reflection and entertainment, not medical, legal or financial advice. No precise Kundli, nakshatra, dasha or transit calculations are offered in this preview.</p><h2>About this release</h2><p>This is the web preview of Astro Zero. AI consultations are not connected.</p></div><button class="button secondary full" data-nav="profile">Back to profile</button>`;
}
document.addEventListener('click',e=>{
 const b=e.target.closest('button');if(!b)return;
 if(b.dataset.nav)navigate(b.dataset.nav);
 if(b.dataset.lesson!==undefined){const l=lessons[+b.dataset.lesson];content.innerHTML=`<button class="textbutton" data-nav="explore">← Back to library</button>`+heading('VEDIC ESSENTIALS · '+l[0],l[1],l[2])+`<div class="card wide learn"><p>${l[3]}</p></div><button class="button full" data-nav="journal">Reflect in your journal ↗</button>`;window.scrollTo(0,0)}
 if(b.dataset.prompt){if(!connected){toast('AI is not connected yet. Explore the Vedic library.');return}$('#question').value=b.dataset.prompt;$('#question').focus()}
 if(b.dataset.delete&&confirm('Delete this reflection? This cannot be undone.')){const next=entries.filter(x=>x.id!==b.dataset.delete);if(save('az-journal',next)){entries=next;render();toast('Reflection deleted')}}
 if(b.id==='delete-all'&&confirm('Delete your profile, journal, consent and current chat? This cannot be undone.')){generation++;localStorage.clear();profile={};entries=[];messages=[];render();toast('All local data deleted')}
 if(b.dataset.report!==undefined){const m=messages[+b.dataset.report];const reason=prompt('Why are you reporting this response? (Do not include personal details.)');if(reason&&reason.trim())request('/report',{response:m.content,reason:reason.slice(0,500)}).then(r=>toast(r.error||'Report received. Thank you.'))}
});
document.addEventListener('submit',async e=>{
 e.preventDefault();
 if(e.target.id==='profile-form'){const p=Object.fromEntries(new FormData(e.target));if(p.birth&&p.birth>new Date().toLocaleDateString('en-CA'))return toast('Please use a birth date in the past.');if(save('az-profile',p)){profile=p;toast('Profile saved');navigate('home')}}
 if(e.target.id==='journal-form'){const text=$('#intention').value.trim();if(!text)return toast('Write a few words first.');const next=[{id:Date.now().toString(),date:new Date().toISOString(),text},...entries];if(save('az-journal',next)){entries=next;render();toast('Reflection saved')}}
 if(e.target.id==='chat-form'){
  if(busy||!connected)return;if(!$('#consent').checked)return toast('Please agree to AI processing before sending.');
  const q=$('#question').value.trim();if(!q)return;save('az-consent',true);const history=messages.slice(-6),currentGeneration=generation;messages.push({role:'user',content:q});busy=true;render();
  const r=await request('/chat',{message:q,history,consent:true});busy=false;if(currentGeneration!==generation)return;
  if(r.error||typeof r.reply!=='string'){messages.pop();render();if($('#question'))$('#question').value=q;toast(r.error||'The guide could not respond. Please try again.')}else{messages.push({role:'assistant',content:r.reply});render()}
 }
});
function request(){return Promise.resolve({error:'AI consultations are not connected yet.'})}
window.addEventListener('popstate',()=>navigate(location.hash.slice(1)||'home'));
navigate(location.hash.slice(1)||'home');
